name: Test and Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v3
      
      # Step 2: Set up Node.js environment
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install
        
      # Step 4: Run tests using Jest
      - name: Run Tests
        run: npm test -- --ci
      
      # Step 5: Build the project, only if tests pass
      - name: Build Project
        run: npm run build
        if: success()  # Ensure the build runs only if the tests pass
